#!/usr/bin/env bash
set -euo pipefail

# Scenario 3 of 3 -- a rented GPU host, Topology A.
#
# The whole VideoOps stack runs on the rented host with ComfyUI bound to
# loopback, so the worker reaches the executor without crossing a network and no
# generated byte travels over a WAN. That is what makes the private-route
# invariant true by construction rather than by configuration.
#
# Rented images ship CUDA and Python but no container runtime, so `pnpm dev` --
# which starts PostgreSQL through docker compose -- cannot run here. This does
# its work directly instead: distribution PostgreSQL, build, migrate, API.
#
# Two ways to invoke it, both supported:
#   from a checkout      bash scripts/setup/gpu-rented.sh
#   on a bare container  --onstart with this file uploaded, or
#                        curl -fsSL <raw URL of this file> | bash
#
# It sets the system up and stops. It rents nothing, submits nothing, and
# destroys nothing -- spending stays a decision you make deliberately.

videoops_repository="${VIDEOOPS_REPOSITORY:-https://github.com/goAustin/AutoCamera.git}"
videoops_root="${VIDEOOPS_ROOT:-/srv/videoops/src}"
comfy_root="${COMFY_ROOT:-/srv/comfyui-h3}"
artifact_root="${ARTIFACT_ROOT:-/srv/videoops/artifacts}"
api_log="${API_LOG:-/var/log/videoops-api.log}"
setup_label="setup (rented GPU)"

die() {
  printf '%s: %s\n' "$setup_label" "$1" >&2
  exit 1
}

step() {
  printf '\n==> %s [%s]\n' "$1" "$(date -u +%H:%M:%SZ)"
}

# Under --onstart there is no terminal, and a failure with no log is the
# expensive kind: the meter runs while you work out what happened.
setup_log="${SETUP_LOG:-/root/videoops-setup.log}"
if [[ ! -t 1 ]] && (: >>"$setup_log") 2>/dev/null; then
  exec > >(tee -a "$setup_log") 2>&1
fi

run_privileged() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

[[ "$(uname -s)" == "Linux" ]] || die "this script targets a Linux GPU host"

# ------------------------------------------------------- system packages -----
step "System packages"
export DEBIAN_FRONTEND=noninteractive
run_privileged apt-get update -qq
# ffmpeg and ffprobe are not optional: the media evaluator shells out to both,
# and without them every attempt fails evaluation and can never be accepted.
run_privileged apt-get install -y -qq \
  git curl ca-certificates gnupg ffmpeg postgresql postgresql-contrib
printf '    %s\n' "$(ffprobe -version 2>/dev/null | head -1)"

node_major=""
if command -v node >/dev/null; then
  node_major="$(node --version)"
  node_major="${node_major#v}"
  node_major="${node_major%%.*}"
fi
if [[ "$node_major" != "24" ]]; then
  step "Node 24"
  curl -fsSL https://deb.nodesource.com/setup_24.x | run_privileged bash -
  run_privileged apt-get install -y -qq nodejs
fi
printf '    node %s\n' "$(node --version)"

# ------------------------------------------------------------ PostgreSQL -----
step "PostgreSQL"
postgres_version="$(ls /etc/postgresql 2>/dev/null | head -1)"
[[ -n "$postgres_version" ]] || die "PostgreSQL did not install"
# No systemd in a container, so the cluster is started directly.
run_privileged pg_ctlcluster "$postgres_version" main start 2>/dev/null ||
  run_privileged service postgresql start >/dev/null 2>&1 || true
for _ in $(seq 1 30); do
  pg_isready -q && break
  sleep 1
done
pg_isready -q || die "PostgreSQL did not become ready"
run_privileged su - postgres -c \
  "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='h3_videoops'\" | grep -q 1" ||
  run_privileged su - postgres -c \
    "psql -q -c \"CREATE ROLE h3_videoops LOGIN PASSWORD 'h3_videoops' SUPERUSER\""
run_privileged su - postgres -c \
  "psql -tAc \"SELECT 1 FROM pg_database WHERE datname='h3_videoops'\" | grep -q 1" ||
  run_privileged su - postgres -c \
    "psql -q -c \"CREATE DATABASE h3_videoops OWNER h3_videoops\""
printf '    %s ready\n' "$(psql --version)"

# ------------------------------------------------------------ the source -----
script_directory=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
if [[ -n "$script_directory" && -f "$script_directory/../../package.json" ]]; then
  videoops_root="$(cd "$script_directory/../.." && pwd)"
elif [[ ! -f "$videoops_root/package.json" ]]; then
  step "VideoOps source"
  run_privileged mkdir -p "$(dirname "$videoops_root")"
  run_privileged chown -R "$(id -u):$(id -g)" "$(dirname "$videoops_root")"
  git clone --quiet "$videoops_repository" "$videoops_root"
fi
cd "$videoops_root"
printf '    source at %s\n' "$videoops_root"

step "Dependencies"
corepack enable >/dev/null 2>&1 || true
corepack prepare "$(node -p "require('./package.json').packageManager")" --activate >/dev/null 2>&1 || true
pnpm install --frozen-lockfile

# --------------------------------------------------------------- executor ----
step "Executor"
COMFY_ROOT="$comfy_root" "$videoops_root/scripts/setup/comfy-executor.sh" --start

# ------------------------------------------------------------ the control ----
step "Control plane"
[[ -f .env ]] || cp .env.example .env
set_env_value() {
  python3 - "$1" "$2" "$3" <<'PYTHON_EOF'
import io, os, sys

path, key, value = sys.argv[1], sys.argv[2], sys.argv[3]
lines = io.open(path, encoding="utf-8").read().splitlines() if os.path.exists(path) else []
replacement = f"{key}={value}"
for index, existing in enumerate(lines):
    if existing.startswith(f"{key}="):
        lines[index] = replacement
        break
else:
    lines.append(replacement)
io.open(path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
PYTHON_EOF
}
mkdir -p "$artifact_root"
set_env_value .env COMFY_MODE remote
set_env_value .env COMFY_BASE_URL http://127.0.0.1:8188
set_env_value .env COMFY_WS_URL ws://127.0.0.1:8188/ws
set_env_value .env COMFY_FRONTEND_URL http://127.0.0.1:8188
# Absolute, and outside the checkout: this is the evidence you copy off before
# teardown, not somewhere to go looking for afterwards.
set_env_value .env ARTIFACT_ROOT "$artifact_root"
# The repository's .env may carry a live DeepSeek key. On a host that is already
# metering a GPU, every operational finding would be a second, separate bill.
set_env_value .env PI_PROVIDER faux

set -a
# shellcheck disable=SC1091
. ./.env
set +a
# tsc -b first, or packages/db migrate cannot resolve @h3/domain.
pnpm build
pnpm db:migrate

if ! curl -fsS http://127.0.0.1:3000/health/live >/dev/null 2>&1; then
  nohup node apps/api/dist/main.js >"$api_log" 2>&1 &
  for _ in $(seq 1 60); do
    curl -fsS http://127.0.0.1:3000/health/live >/dev/null 2>&1 && break
    sleep 1
  done
fi
curl -fsS http://127.0.0.1:3000/health/ready >/dev/null 2>&1 ||
  die "the API did not become ready; see $api_log"
printf '    %s\n' "$(curl -fsS http://127.0.0.1:3000/health/ready)"

# ------------------------------------------------------------- readiness -----
step "Readiness"
printf '    listening:\n'
ss -ltnp 2>/dev/null | grep -E ':8188|:3000' | sed 's/^/      /' || true
python3 - <<'PYTHON_EOF'
import json, urllib.request

def get(path, base="http://127.0.0.1:8188"):
    with urllib.request.urlopen(base + path, timeout=30) as response:
        return json.load(response)

object_info = get("/object_info")
required = json.load(open("workflows/minimax-h3/compatibility-manifest.json"))["requiredApiNodeClasses"]
missing = [name for name in required if name not in object_info]
stats = get("/system_stats")
print(f"    ComfyUI {stats['system'].get('comfyui_version')} / torch {stats['system'].get('pytorch_version')}")
print(f"    device  {stats['devices'][0]['name']}")
print(f"    classes {len(required) - len(missing)}/{len(required)} required present"
      + (f" -- MISSING {missing}" if missing else ""))
if missing:
    raise SystemExit("    the executor cannot run the pinned graph; do not submit a run")
PYTHON_EOF
printf '    executor: %s\n' \
  "$(curl -fsS http://127.0.0.1:3000/v1/executor -H "authorization: Bearer ${DEV_AUTH_TOKEN:-dev-token}")"

# ------------------------------------------------------------------ next -----
cat <<'GUIDE_EOF'

==> Ready. Nothing has been submitted and nothing is being generated.

    Arm the budget before the first run. POST /v1/runs without a projectId
    auto-creates a project with budgetMicrousd: null, which enforces nothing:

      curl -sS -X POST http://127.0.0.1:3000/v1/projects \
        -H "authorization: Bearer $DEV_AUTH_TOKEN" \
        -H 'content-type: application/json' \
        -H 'idempotency-key: session-project' \
        -d '{"title":"Session","brief":"Rented GPU session",
             "targetDurationSeconds":5,"budgetUsd":"3.00"}'

    Submit every run against that projectId.

    Before teardown, copy the evidence off this host -- it is destroyed with it:
      ARTIFACT_ROOT, a pg_dump of h3_videoops, and the logs.

    Then destroy the instance. Stopping it keeps billing for the disk.
GUIDE_EOF
